### PR TITLE
Docker deployments to dockerhub

### PR DESCRIPTION
**Pull request by zaro0508**
Setup automated docker container deployments to the official
Sage dockerhub repository at
https://hub.docker.com/u/sagebionetworks/dashboard/

### CODE REVIEW

**Comment by zaro0508** [comment]
@ Zaknarfen please review

**Comment by Zaknarfen** [comment]
@zaro0508 I think it is just a matter of adding `sudo` to [this](https://github.com/Sage-Bionetworks/Agora/blob/fb6bbea2c4d6a11b08f77d7bb8f0fb53de75b7c0/.travis.yml#L28) line to fix it. It would be great if you merged to develop also, then we merge to master with the current developments.

**Review by Zaknarfen — APPROVED** [review]
Looks good.

**Comment by zaro0508** [comment]
replaced with PR https://github.com/Sage-Bionetworks/Agora/pull/427

**Pull request closed without merging**
